{% set name = "google-cloud-compute" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a67857918497a61eda219268237b574cd214907e384b6d900c8197525f5c7855

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

# an additional runtime dependency of dataclasses is necessary for Python 3.6,
# conda-forge stopped building 3.6 so we impose a 3.7 requirement to prevent
# upgrades of older systems
requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - google-api-core-grpc >=2.10.2,<3.0.0dev
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.api_core
    - google.cloud
    - google.cloud.compute
    - grpc
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-compute
  summary: Python Client for Google Cloud Compute Engine
  doc_url: https://googleapis.dev/python/compute/latest/index.html
  dev_url: https://github.com/googleapis/python-compute
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tpdownes
    - tswast
